server:
  port: 8030
logging:
  level.root: info
  path: logs
  file: ${spring.application.name}.log
spring:
  application:
    name: ibase-service
  datasource:
    url: jdbc:mysql://10.7.12.222:3306/springcloud?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  errorcode:
    messages:
      basename: i18n/messages/errorcode/ibase_errorcode_message
      encoding: UTF-8
  operatelog:
    messages:
      basename: i18n/messages/operatelogcode/ibase_operate_message
      encoding: UTF-8
  cloud:
    stream:
      binders:
        defaultRabbit: # 表示定义的名称，用于于binding整合
          environment:
            spring:
              rabbitmq:
                host: 10.7.12.222
                port: 5672
                username: guest
                password: guest
iauth-client:
  url: 127.0.0.1:8020
ibase-client:
  url: 127.0.0.1:8030