server:
  port: 7979
spring:
  application:
    name: apigateway  
logging:
  level.root: info
  file: logs/${spring.application.name}.log
iauth-client:
  url: 127.0.0.1:8020
zuul:
  routes:
    iauth:
      path: /iauth/**
      url: http://127.0.0.1:8020
      stripPrefix: true
    ibase:
      path: /ibase/**
      url: http://127.0.0.1:8030
      stripPrefix: true
    icompute:
      path: /icompute/**
      url: http://127.0.0.1:8050
      stripPrefix: true
    itask:
      path: /itask/**
      url: http://127.0.0.1:8060
      stripPrefix: true