server:
  port: 8030

spring:
  application:
    name: ibase-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.7.12.222:3306/springcloud?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
    show-sql: true

  
flyway:
  enabled: true
  checkLocation: true
  locations: classpath:db/migration
  table: ibase_schema
  validateOnMigrate: true
  cleanOnValidationError: true
  baselineOnMigrate: true
  baselineVersion: 0